typography_spectrum: 0.6953888728749007
color:
  brandStrength: 0.10467146895825863
  lightness: 0.21173383831046522
  saturation: 0.5379514636006206
  rhythmicContrast: 0.2716627726331353
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8895098816137761
name: stefanherzogtesting
title: Test the AI web designer
description: Does it work?
